# Generated by Django 4.2.25 on 2025-10-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_medicine_pharmacy'),
        ('orders', '0003_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.pharmacy'),
        ),
    ]
