# Generated by Django 4.2.17 on 2025-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance',
            field=models.FloatField(default=0, help_text='Distance traveled in km'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='expected_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Planned delivery time', null=True),
        ),
    ]
