# Generated by Django 4.2.17 on 2025-10-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_deliveryproof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryProof',
        ),
    ]
