# Generated by Django 4.2.17 on 2025-10-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_delete_deliveryproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
