# Generated by Django 4.2.17 on 2025-10-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_medicine_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
