# Generated by Django 4.2.17 on 2025-10-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_medicine_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
