# Generated by Django 4.2.25 on 2025-11-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_stock_expiry_date_pharmacy_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
