# Generated by Django 4.2.25 on 2025-11-28 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_pharmacy_alter_orderitem_pharmacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_alter_pharmacy_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
