# Generated by Django 4.2.17 on 2025-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('delivery', 'Delivery'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
