# Generated by Django 4.2.25 on 2025-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('delivery', 'Delivery')], default='admin', max_length=20),
        ),
    ]
