# Generated by Django 4.2.25 on 2025-11-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_approved_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Public User'), ('pharmacist', 'Pharmacist'), ('delivery', 'Delivery Man')], default='admin', max_length=20),
        ),
    ]
