# Generated by Django 4.2.27 on 2025-12-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Public User'), ('pharmacist', 'Pharmacist')], default='admin', max_length=20),
        ),
    ]
