# Generated by Django 4.2.17 on 2025-12-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
